#pragma once

#include "source2sdk/source2gen/source2gen.hpp"
#include <cstddef>
#include <cstdint>

// /////////////////////////////////////////////////////////////
// Module: client
// Created using source2gen - github.com/neverlosecc/source2gen
// /////////////////////////////////////////////////////////////

namespace source2sdk
{
    namespace client
    {
        // Enumerator count: 97
        // Alignment: 4
        // Size: 0x4
        enum class Class_T : std::uint32_t
        {
            CLASS_NONE = 0x0,
            CLASS_PLAYER = 0x1,
            CLASS_PLAYER_ALLY = 0x2,
            CLASS_MODIFIER_THINKER = 0x3,
            CLASS_TROOPER = 0x4,
            CLASS_TROOPER_BOSS = 0x5,
            CLASS_TROOPER_NEUTRAL = 0x6,
            CLASS_TROOPER_FLYING_WEAKPOINT = 0x7,
            CLASS_SUPER_NEUTRAL = 0x8,
            CLASS_ITEM_SHOP = 0x9,
            CLASS_ABILITY_SHOP = 0xa,
            CLASS_MINI_MAP_MARKER = 0xb,
            CLASS_ABILITY = 0xc,
            CLASS_ABILITY_PROJECTILE = 0xd,
            CLASS_CRATE = 0xe,
            CLASS_CRATE_SPAWN = 0xf,
            CLASS_PICKUP_SPAWN = 0x10,
            CLASS_FLARE = 0x11,
            CLASS_SPAWNED_DRONE = 0x12,
            CLASS_ROLLERMINE = 0x13,
            CLASS_PERCHED_PREDATOR_PROJECTILE = 0x14,
            CLASS_PARACHUTE = 0x15,
            CLASS_SENTRY = 0x16,
            CLASS_BASE_SENTRY = 0x17,
            CLASS_DISPENSER = 0x18,
            CLASS_SPY_DRONE = 0x19,
            CLASS_GOLD_ORB = 0x1a,
            CLASS_ZIP_LINE_NODE = 0x1b,
            CLASS_DESTROYABLE_BUILDING = 0x1c,
            CLASS_BOSS_TIER_2 = 0x1d,
            CLASS_BOSS_BARRACKS = 0x1e,
            CLASS_BOSS_TIER_3 = 0x1f,
            CLASS_BOSS_TIER_3_DRONE = 0x20,
            CLASS_ANNOUNCER = 0x21,
            CLASS_WEAK_NEUTRAL_CAMP = 0x22,
            CLASS_MEDIUM_NEUTRAL_CAMP = 0x23,
            CLASS_STRONG_NEUTRAL_CAMP = 0x24,
            CLASS_VAULT_NEUTRAL_CAMP = 0x25,
            CLASS_SUPER_NEUTRAL_CAMP = 0x26,
            CLASS_EXPLOSIVE_BARREL = 0x27,
            CLASS_PAYLOAD = 0x28,
            CLASS_BULLET_TIME_WARP = 0x29,
            CLASS_BREAKABLE_PROP_PICKUP = 0x2a,
            CLASS_PUNCHABLE_POWERUP = 0x2b,
            CLASS_ITEM_PICKUP = 0x2c,
            CLASS_GOLDEN_IDOL_PICKUP = 0x2d,
            CLASS_HERO_CLONE = 0x2e,
            CLASS_TRIGGER_HURT = 0x2f,
            CLASS_DRONE_DISPENSER = 0x30,
            CLASS_HERO_MINION = 0x31,
            CLASS_PING_MARKER = 0x32,
            CLASS_PING_LOCATION_TRIGGER = 0x33,
            CLASS_TESLA_COIL = 0x34,
            CLASS_DIRECTOR_CAMERA = 0x35,
            CLASS_BREAKABLE_PROP = 0x36,
            CLASS_TRIGGER_IDOL_RETURN = 0x37,
            CLASS_TRIGGER_SHOP_TUNNEL = 0x38,
            CLASS_TRIGGER_TELEPORT = 0x39,
            CLASS_TRIGGER_MODIFIER = 0x3a,
            CLASS_TRIGGER_OBSCURED_VOLUME = 0x3b,
            CLASS_TRIGGER_ZIPLINE_CAPTURE = 0x3c,
            CLASS_TRIGGER_CATAPULT = 0x3d,
            CLASS_TRIGGER_CLIMB_ROPE = 0x3e,
            CLASS_ICEPATH_SHARD = 0x3f,
            CLASS_GUIDED_ARROW = 0x40,
            CLASS_PING_LOCATION = 0x41,
            CLASS_DUSTSTORM_PROJECTILE = 0x42,
            CLASS_CYCLONE_PROJECTILE = 0x43,
            CLASS_FIELD_SENTRY = 0x44,
            CLASS_ZAP_TRIGGER = 0x45,
            CLASS_VISCOUS_CUBE = 0x46,
            CLASS_FISSURE_WALL_SEGMENT = 0x47,
            CLASS_NANO_STATUE = 0x48,
            CLASS_TRAPPER_SPIDER = 0x49,
            CLASS_TRAPPER_WEBWALL = 0x4a,
            CLASS_IMMOBILIZE_TRAP_PROJECTILE = 0x4b,
            CLASS_MAGICIAN_TURRET = 0x4c,
            CLASS_MID_STAIRS = 0x4d,
            CLASS_PROP_MIDBOSS_INDICATOR = 0x4e,
            CLASS_VAMPIREBAT_BATSWARM = 0x4f,
            CLASS_VAMPIREBAT_BATSWARM_EXTRA = 0x50,
            CLASS_TRIGGER_HIDEOUT = 0x51,
            CLASS_SWAN_FEATHERBOOMERANG = 0x52,
            CLASS_BULLET_REDIRECT_VOLUME = 0x53,
            CLASS_BOOKWORM_KNIGHTCHARGE = 0x54,
            CLASS_DOORMAN_DOORWAY = 0x55,
            CLASS_HIDEOUT_INTERACTABLE_PROP = 0x56,
            CLASS_HIDEOUT_INTERACTABLE_TRIGGER = 0x57,
            CLASS_CAPTURE_POINT = 0x58,
            CLASS_ESCORT = 0x59,
            CLASS_TIER2 = 0x5a,
            CLASS_NPC_FLYING_PIGEON = 0x5b,
            CLASS_NPC_HIDEOUT_CAT = 0x5c,
            CLASS_HIDEOUT_BALL = 0x5d,
            CLASS_SHIELD = 0x5e,
            CLASS_TRIGGER_NO_PORTALS = 0x5f,
            NUM_CLASSIFY_CLASSES = 0x60,
        };
    };
};
